name: "IntegrationTest"

on:
  push:
    branches:
      - 'main'
    tags: '*'
  pull_request:

jobs:
  integration-test:
    name: "IntegrationTest"
    strategy:
       matrix:
         repo:
{DOWNSTREAMPKGS}
    uses: "ITensor/ITensorActions/.github/workflows/IntegrationTest.yml@main"
    with:
      localregistry: "https://github.com/ITensor/ITensorRegistry.git"
      repo: "${{ matrix.repo }}"
