name: "Literate Check"

on:
  push:
    branches:
      - 'main'
    tags: '*'
  pull_request:

jobs:
  literate:
    name: "Literate Check"
    uses: "ITensor/JuliaActions/workflows/LiterateCheck.yml@main"
    with:
      localregistry: https://github.com/ITensor/ITensorRegistry.git
